# fly.toml app configuration file generated for debug-deploy-issue-4 on 2023-06-06T10:13:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "debug-deploy-issue-4"
primary_region = "bos"
console_command = "/rails/bin/rails console"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
